# This file can be used to customize the files managed by PDK.
#
# See https://github.com/puppetlabs/pdk-templates/blob/main/README.md
# for more information.
#
# See https://github.com/puppetlabs/pdk-templates/blob/main/config_defaults.yml
# for the default values.
---
.gitignore:
  paths: 
  - ".vscode/"
  - ".cache/"
  - ".config/"
Rakefile:
  default_disabled_lint_checks:
    - 140chars
spec/spec_helper.rb:
  minimum_code_coverage_percentage: 100
