name: Puppet 7 validations
run-name: ${{ github.actor }} is running Puppet 7 validations
on:
  - push
  - pull_request
jobs:
  lint:
    runs-on: ubuntu-latest
    container: puppet/pdk:3.3.0.0
    steps:
      - name: Clone repository
        uses: actions/checkout@v4
      - name: PDK syntax validation
        run: pdk validate --puppet-version=7 --format=text --parallel
  unit_tests:
    runs-on: ubuntu-latest
    container: puppet/pdk:3.3.0.0
    steps:
      - name: Clone repository
        uses: actions/checkout@v4
      - name: PDK unit tests
        run: pdk test unit --puppet-version=7 --format=junit:pdk7.xml --format=text --parallel
      - name: Publish Test Report
        uses: mikepenz/action-junit-report@v5
        with:
          report_paths: "pdk7.xml"
          include_passed: true
        if: ${{ always() }}
permissions:
  checks: write
