name: TemplateUpdater

on:
  # schedule:
  #   - cron: '0 4 * * 1' # Every Monday at 4 AM
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  update-templates:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Vox Pupuli Configs
        uses: actions/checkout@v7
        with:
          repository: voxpupuli/modulesync_config
          path: modulesync_config

      - name: Checkout our module
        uses: actions/checkout@v7
        with:
          path: modulesync_config/modules/philippeganz/puppet-stunnel
          fetch-depth: 0

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3'
          working-directory: modulesync_config

      - name: Install ModuleSync
        working-directory: modulesync_config
        run: bundle install

      - name: Setup isolated fleet config
        working-directory: modulesync_config
        run: |
          echo "---" > managed_modules.yml
          echo "- puppet-stunnel" >> managed_modules.yml

      - name: Run ModuleSync
        working-directory: modulesync_config
        run: bundle exec msync update --offline --noop -n philippeganz -f puppet-stunnel

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v8
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          path: modulesync_config/modules/philippeganz/puppet-stunnel
          commit-message: 'Update templates via vox pupuli'
          title: 'chore: update templates via vox pupuli'
          branch: template-updates
          body: |
            This PR automatically applies the latest Vox Pupuli templates using ModuleSync.
          labels: |
            maintenance
