name: TemplateUpdater

on:
  # schedule:
  #   - cron: '0 4 * * 1' # Every Monday at 4 AM
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  modulesync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v7
        with:
          fetch-depth: 0

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.3'

      - name: Install Vox Pupuli Jig
        run: |
          curl -sL https://github.com/voxpupuli/jig/releases/latest/download/jig_Linux_x86_64.tar.gz | tar -xz
          sudo mv jig /usr/local/bin/

      - name: Update from Vox Pupuli Templates
        run: jig update --force --template-url https://github.com/voxpupuli/pdk-templates

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v8
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: 'chore: update templates via vox pupuli'
          title: 'chore: update templates via vox pupuli'
          branch: template-updates
          body: |
            This PR automatically applies the latest Vox Pupuli templates using the open-source PDK CLI.
          labels: |
            maintenance
