name: TemplateUpdater

on:
  # schedule:
  #   - cron: '0 4 * * 1' # Every Monday at 4 AM
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  update-templates:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v7
        with:
          fetch-depth: 0

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3'

      - name: Install PDK
        run: gem install pdk

      - name: Update from Vox Pupuli Templates
        run: pdk update --force

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v8
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: 'chore: update templates via vox pupuli'
          title: 'chore: update templates via vox pupuli'
          branch: template-updates
          body: |
            This PR automatically applies the latest Vox Pupuli templates using the open-source PDK CLI.
          labels: |
            maintenance
