name: Puppet unit tests
run-name: ${{ github.actor }} is running Puppet unit tests
on:
  - push
  - pull_request
jobs:
  unit:
    runs-on: ubuntu-latest
    container: puppet/pdk:latest
    steps:
    - name: Clone repository
      uses: actions/checkout@v3
    - name: pdk test unit
      run: pdk test unit --puppet-version=7